//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Doppler.languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class FormStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FormStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Doppler.languages.FormStrings", typeof(FormStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to active feeds.
        /// </summary>
        internal static string activefeeds {
            get {
                return ResourceManager.GetString("activefeeds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Add feed.
        /// </summary>
        internal static string Addfeed {
            get {
                return ResourceManager.GetString("Addfeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add to Apple iTunes.
        /// </summary>
        internal static string AddToAppleiTunes {
            get {
                return ResourceManager.GetString("AddToAppleiTunes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add to M3U.
        /// </summary>
        internal static string AddToM3U {
            get {
                return ResourceManager.GetString("AddToM3U", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add to Windows Media Player.
        /// </summary>
        internal static string AddToWindowsMediaPlayer {
            get {
                return ResourceManager.GetString("AddToWindowsMediaPlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adjust volume.
        /// </summary>
        internal static string Adjustvolume {
            get {
                return ResourceManager.GetString("Adjustvolume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All files.
        /// </summary>
        internal static string AllFiles {
            get {
                return ResourceManager.GetString("AllFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured. Double click to enable logging and do a new retrieve..
        /// </summary>
        internal static string AnerroroccuredEnablelogginganddoanewretrieve {
            get {
                return ResourceManager.GetString("AnerroroccuredEnablelogginganddoanewretrieve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured. Double click to open the log file.
        /// </summary>
        internal static string AnerroroccuredPleasecheckthelogfile {
            get {
                return ResourceManager.GetString("AnerroroccuredPleasecheckthelogfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured while checking for the latest version
        ///
        ///.
        /// </summary>
        internal static string AnErrorOccuredWhileCheckingForTheLatestVersion {
            get {
                return ResourceManager.GetString("AnErrorOccuredWhileCheckingForTheLatestVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred: {0}.
        /// </summary>
        internal static string Anerroroccurred {
            get {
                return ResourceManager.GetString("Anerroroccurred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete the {0} selected feeds?.
        /// </summary>
        internal static string Areyousureyourwanttodeletethexselectedfeeds {
            get {
                return ResourceManager.GetString("Areyousureyourwanttodeletethexselectedfeeds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete these files?.
        /// </summary>
        internal static string Areyousureyouwanttodeletethesefiles {
            get {
                return ResourceManager.GetString("Areyousureyouwanttodeletethesefiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this feed subscription?.
        /// </summary>
        internal static string Areyousureyouwanttodeletethisfeedsubscription {
            get {
                return ResourceManager.GetString("Areyousureyouwanttodeletethisfeedsubscription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this file?.
        /// </summary>
        internal static string Areyousureyouwanttodeletethisfile {
            get {
                return ResourceManager.GetString("Areyousureyouwanttodeletethisfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot delete file, access denied.
        /// </summary>
        internal static string CannotDeleteFileAccessDenied {
            get {
                return ResourceManager.GetString("CannotDeleteFileAccessDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to change position.
        /// </summary>
        internal static string Clicktochangeposition {
            get {
                return ResourceManager.GetString("Clicktochangeposition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Converting to bookmarkable AAC.
        /// </summary>
        internal static string ConvertingtobookmarkableAAC {
            get {
                return ResourceManager.GetString("ConvertingtobookmarkableAAC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom.
        /// </summary>
        internal static string CustomAction {
            get {
                return ResourceManager.GetString("CustomAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete subscription.
        /// </summary>
        internal static string Deletesubscription {
            get {
                return ResourceManager.GetString("Deletesubscription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Determining size of {0}.
        /// </summary>
        internal static string Determiningsizeofx {
            get {
                return ResourceManager.GetString("Determiningsizeofx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doppler needs a download folder. As you did not specify a download folder, Doppler will assume one for you. 
        ///
        ///.
        /// </summary>
        internal static string DopplerNeedsADownloadFolderAsYouDidNotSpecifyADownloadFolderDopplerWillAssumeOneForYou {
            get {
                return ResourceManager.GetString("DopplerNeedsADownloadFolderAsYouDidNotSpecifyADownloadFolderDopplerWillAssumeOneF" +
                        "orYou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Double click an entry to cancel or skip the download.
        /// </summary>
        internal static string DoubleClickAnEntryToCancelOrSkipTheDownload {
            get {
                return ResourceManager.GetString("DoubleClickAnEntryToCancelOrSkipTheDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download aborted.
        /// </summary>
        internal static string Downloadaborted {
            get {
                return ResourceManager.GetString("Downloadaborted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloaded a new podcast from {0}.
        /// </summary>
        internal static string Downloadedanewpodcastfrom {
            get {
                return ResourceManager.GetString("Downloadedanewpodcastfrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download from {0} aborted.
        /// </summary>
        internal static string Downloadfromaborted {
            get {
                return ResourceManager.GetString("Downloadfromaborted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to retrieve {0} from {1} later?.
        /// </summary>
        internal static string DoYouWantToRetrieve0From1Later {
            get {
                return ResourceManager.GetString("DoYouWantToRetrieve0From1Later", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error adding feed.
        /// </summary>
        internal static string ErrorAddingFeed {
            get {
                return ResourceManager.GetString("ErrorAddingFeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error during catch-up.
        /// </summary>
        internal static string ErrorDuringCatchUp {
            get {
                return ResourceManager.GetString("ErrorDuringCatchUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while adding file to playlist in Windows Media Player.
        /// </summary>
        internal static string ErrorWhileAddingFileToPlaylistInWindowsMediaPlayer {
            get {
                return ResourceManager.GetString("ErrorWhileAddingFileToPlaylistInWindowsMediaPlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while downloading from {0}.
        /// </summary>
        internal static string Errorwhiledownloadingfrom {
            get {
                return ResourceManager.GetString("Errorwhiledownloadingfrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} feeds subscribed.
        /// </summary>
        internal static string FeedsSubscribed {
            get {
                return ResourceManager.GetString("FeedsSubscribed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} feeds subscribed, {1} new podcasts in feeds.
        /// </summary>
        internal static string FeedsSubscribedNewPodcastsInFeeds {
            get {
                return ResourceManager.GetString("FeedsSubscribedNewPodcastsInFeeds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First retrieve some files.
        /// </summary>
        internal static string Firstretrievesomefiles {
            get {
                return ResourceManager.GetString("Firstretrievesomefiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hours.
        /// </summary>
        internal static string hours {
            get {
                return ResourceManager.GetString("hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import OPML file.
        /// </summary>
        internal static string ImportOPMLFile {
            get {
                return ResourceManager.GetString("ImportOPMLFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initializing session.
        /// </summary>
        internal static string Initializingsession {
            get {
                return ResourceManager.GetString("Initializingsession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iTunes is busy, please close all dialogboxes in iTunes.
        /// </summary>
        internal static string ITunesIsBusyPleaseCloseAllDialogboxesInITunes {
            get {
                return ResourceManager.GetString("ITunesIsBusyPleaseCloseAllDialogboxesInITunes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;leave empty to extract name from the feed&gt;.
        /// </summary>
        internal static string LeaveEmptyToExtractNameFromTheFeed {
            get {
                return ResourceManager.GetString("LeaveEmptyToExtractNameFromTheFeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;leave empty to use feed name&gt;.
        /// </summary>
        internal static string LeaveEmptyToUseFeedName {
            get {
                return ResourceManager.GetString("LeaveEmptyToUseFeedName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logging has been enabled and errors will show up in the log from now on..
        /// </summary>
        internal static string LoggingHasBeenEnabledAndErrorsWillShowUpInTheLogFromNowOn {
            get {
                return ResourceManager.GetString("LoggingHasBeenEnabledAndErrorsWillShowUpInTheLogFromNowOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logging is current disabled. Do you want to enable the log to record errors?.
        /// </summary>
        internal static string LoggingIsCurrentDisabledDoYouWantToEnableTheLogToRecordErrors {
            get {
                return ResourceManager.GetString("LoggingIsCurrentDisabledDoYouWantToEnableTheLogToRecordErrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to minutes.
        /// </summary>
        internal static string minutes {
            get {
                return ResourceManager.GetString("minutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New download.
        /// </summary>
        internal static string Newdownload {
            get {
                return ResourceManager.GetString("Newdownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to new.
        /// </summary>
        internal static string newfeed {
            get {
                return ResourceManager.GetString("newfeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New version.
        /// </summary>
        internal static string NewVersion {
            get {
                return ResourceManager.GetString("NewVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A new version of Doppler is available. Do you want go to the website and download the new version?.
        /// </summary>
        internal static string NewVersionOfDopplerAvailable {
            get {
                return ResourceManager.GetString("NewVersionOfDopplerAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        internal static string NoAction {
            get {
                return ResourceManager.GetString("NoAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No active downloads.
        /// </summary>
        internal static string Noactivedownloads {
            get {
                return ResourceManager.GetString("Noactivedownloads", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No OPML directories available.
        /// </summary>
        internal static string Nodirectoriesavailable {
            get {
                return ResourceManager.GetString("Nodirectoriesavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No download folder?.
        /// </summary>
        internal static string NoDownloadFolder {
            get {
                return ResourceManager.GetString("NoDownloadFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No folder available.
        /// </summary>
        internal static string Nofolderavailable {
            get {
                return ResourceManager.GetString("Nofolderavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No folder available. Retrieve this feed first..
        /// </summary>
        internal static string NofolderavailableRetrievethisfeedfirst {
            get {
                return ResourceManager.GetString("NofolderavailableRetrievethisfeedfirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No new version.
        /// </summary>
        internal static string NoNewVersion {
            get {
                return ResourceManager.GetString("NoNewVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not a valid feed. Check the log for more information..
        /// </summary>
        internal static string NotAValidFeedCheckTheLogForMoreInformation {
            get {
                return ResourceManager.GetString("NotAValidFeedCheckTheLogForMoreInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No title specified.
        /// </summary>
        internal static string NoTitleSpecified {
            get {
                return ResourceManager.GetString("NoTitleSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OPML files.
        /// </summary>
        internal static string OPMLFiles {
            get {
                return ResourceManager.GetString("OPMLFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parsing feeds....
        /// </summary>
        internal static string Parsingfeeds {
            get {
                return ResourceManager.GetString("Parsingfeeds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parsing RSS items {0} of {1}.
        /// </summary>
        internal static string ParsingRSSItemxofy {
            get {
                return ResourceManager.GetString("ParsingRSSItemxofy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please add some OPML directories first in the options.
        /// </summary>
        internal static string PleaseaddsomeOPMLdirectoriesfirstintheoptions {
            get {
                return ResourceManager.GetString("PleaseaddsomeOPMLdirectoriesfirstintheoptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retrieving feeds....
        /// </summary>
        internal static string Retrievingfeeds {
            get {
                return ResourceManager.GetString("Retrievingfeeds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retrieving... please wait.
        /// </summary>
        internal static string RetrievingPleaseWait {
            get {
                return ResourceManager.GetString("RetrievingPleaseWait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retrieving RSS.
        /// </summary>
        internal static string RetrievingRSS {
            get {
                return ResourceManager.GetString("RetrievingRSS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - scheduled -.
        /// </summary>
        internal static string Scheduled {
            get {
                return ResourceManager.GetString("Scheduled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Directory.
        /// </summary>
        internal static string SelectDirectory {
            get {
                return ResourceManager.GetString("SelectDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Succesfully deleted {0} cache file(s).
        /// </summary>
        internal static string SuccesfullyDeletedCacheFiles {
            get {
                return ResourceManager.GetString("SuccesfullyDeletedCacheFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temporary download channel.
        /// </summary>
        internal static string TemporaryDownloadChannel {
            get {
                return ResourceManager.GetString("TemporaryDownloadChannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The folder picked is: .
        /// </summary>
        internal static string TheFolderPickedIs {
            get {
                return ResourceManager.GetString("TheFolderPickedIs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uncategorized.
        /// </summary>
        internal static string Uncategorized {
            get {
                return ResourceManager.GetString("Uncategorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        internal static string Unknown {
            get {
                return ResourceManager.GetString("Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Update Feed.
        /// </summary>
        internal static string UpdateFeed {
            get {
                return ResourceManager.GetString("UpdateFeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting in queue for conversion.
        /// </summary>
        internal static string Waitinginqueueforconversion {
            get {
                return ResourceManager.GetString("Waitinginqueueforconversion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} while downloading {1}.
        /// </summary>
        internal static string xWhileDownloadingy {
            get {
                return ResourceManager.GetString("xWhileDownloadingy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are running the latest version of Doppler.
        /// </summary>
        internal static string YouAreRunningTheLatestVersionOfDoppler {
            get {
                return ResourceManager.GetString("YouAreRunningTheLatestVersionOfDoppler", resourceCulture);
            }
        }
    }
}
